### az language template strings for Broadcaster 1.1 ### 

editArticle = "mətni dəyiş"
premium = "premium*"
comments = "şərh(lər)"
by = "tərəfindən"
readMore = "ardı"
addComment = "Şərh yaz"
previous = "əvvəlki"
next = "növbəti"
page = "səhifə"
photo = "şəkil:"
welcome = "Xoş gəlmisiz"
language = "dil:"
MakeYourOwnRadio = "Öz radionu yarat"
CallForParticipation = "İştirak üçün müraciyyət"
Join = "Bizə qoşul!"
articleGallery = "Məqalələr"
storyPlaces = "Yerlər"
listenAudio = "Audio dinlə"
downloadAudioFile = "Audio faylı yüklə"
watchVideo = "Videoya bax"
download = "Yüklə"
file = "fayl"
downloadFile = "Faylı yüklə"
fileOfType = "Fayl növü:"
alsoIn = "həmçinin"
relatedStories = "oxşar"

viewProfile = "Profilə bax"

somethingToSay = "Nəsə de"
writeComment = "Şərh yaz"
anonymous = "(Məxvi)"
writeAComment = "şərj yaz"
commentNotAccepted = "Şərhiniz qəbul olunmamışdır"
commentSentApproval = "Şərhiniz təstiq üçün göndərilmişdir."
publish = "Dərc et"
commentsLockedDisabled = "Şərhlər bağlıdır/bu yazı üçün bağlıdır."
haveToRegister = "Yazılara şərh yazmaq üçün və ya komandamıza mesaj yazmaq üçün qeydiyyatdan keçməlisiz. Xahiş edirik daxil olun və pulsuz qeydiyyatdan keçin"
commentPlaceholder = "Şərhinizi bura yazın"
nicknamePlaceholder = "İstifadəçi adı"
emailPlaceholder = "e-mailiiz"
thisArticleIsLocked = "Bu yazı bağlıdır. Yalnız qeydiyyatlı istifadəçilər üçün"


articleRating = "Yazının reytinqi:"
voteData = "səslər haqqda"
voteS = "səs."
averageRating = "orta səs:"


debateVoting = "şərhə səs"
changeYourMind = "Bu müzakirə bitənə qədər fikirini nə qədər istəsən dəyişə bilərsən. Bir tərədin fikiri o birisindən daha güclü gələrsə"
debateClosed = "Müzakirə bağlıdır. Son qərar verilib."
pleaseLoginVote = "Səs vermək üçün daxil olun"


proArgumentsBy = "Razılaşanlar:"
contraArgumentsBy = "Razılaşmayanlar:"


chartsTitle = "Bölmə: 30 ən"

latestLocations = "son məkanlar"

onAirNow = "İndi efirdə"
aboutUs = "Haqqımızda"
latestNews = "Son xəbərlər"

content = "İçindəkilər"
logout = "Çıx"
login = "Daxil ol"
followUs = "Bizi izlə"
followAtTwitter = "Bizi Twitter-də izlə"
likeOnFacebook = "Bizi Facebook-da bəyən"
signupRSS = " RSS-a qoşul"
shareThis = "Paylaş"
tweetOnTwitter = "Tweeter-ə yaz"
postToFacebook = "Facebook-da paylaş"
shareGooglePlus = "Google+da paylaş"

listenLive = "Canlı dinlə"
playNow = "Oxud"
current = "İndi:"

hostedBy = "Hosted by:"
podcast = "Podkast"
archive = "Arxiv"

programGrid = "Verlişlər siyahısı"

year = "İl"
yearS = "İl"
month = "Ay"
monthS = "Ay"
day = "Gün"
dayS = "Gün"
hours = "s"
minutes = "dəq"
seconds = "san"
ago = "əvvəl"

searchResults = "Axtarış nəticələri"
noSearchResults = "Heç bir şey tapılşmamışdır."

section = "Bölmə:"
moreStories = "Daha çox "

mostRead = "Ən çox oxunan"
communityFeed = "Lent"
newCommentOn = "-də yeni şərh:"


topic = "Mövzu:"
moreThisTopic = "Bu mövzuya aid daha çox"
articlesBy = "məqalələri"
moreVideos = "Daha çox video"
issuesArchive = "Mövzunun arxivi"

loginFailed = "Giriş alınmadı"
eitherEmailPassword = "Ya e-mailiniz ya parolunuz səhvdir"
tryAgain = "Bir də cəhd edin!"
forgotPassword = "Parolunuzu unutmusuz?"
password = "Parol"
register = "Qeydiyyat"

resetPassword = "Parolu bir də təyin et"
emailNotCorrect = "E-mail düzgün deyil"
maybeRegisteredOn = "Bəlkə siz başqa cür qeydiyyatdan keçmisiz:"
withAnotherEmail = "digər e-mail ilə?"
requestNewPassword = "Yeni parol istə"

userAccount = "İstifadəçi"
weSentEmail = "Biz sizə e-mail göndərdik"
pleaseCheckInbox = "Zəhmət olmasa e-mailinizi yoxlayın və verilmiş linkə keçin."

setNewPassword = "Yeni parol təyin et"
passCouldntChange = "Sizin parolunuz dəyişilə bilməz. Zəhmət olmsa oxuyun və yenidən cəhd edin"
newPassLabel = "Yeni parol"
pleaseEnterNewPass = "Zəhmət olmasa yeni parоlunuzu yazın (minimum 6 hərf)"
retypePassLabel = "Parolunuzu bir də yazın"
confirmDoesntMatch = "Yazdığınız parollar uyğun gəlmir."
savePassButton = "Parolu yadda saxla"

mailHello = "Salam,"
mailAutomaticalMessage = "Bu [name] - dən yaranmış avtomatik mesajdır"
mailPleaseConfirm = "Zəhmət olmasa aşağıdakı linkə tıklayaraq e-mailinizi təstiqləyin:"
mailOtherwise = "Əgər bu məktubun sizə göndərilməsini istəməmisizsə zəhmət omasa bu mesajı pozun"
mailThanks = "Çox sağ olun!"

confirmSent = "Təstiq göndərilmişdir"
followEmailSteps = "E-mailda tapacağınız izahatları izləyin."
thanksForRegistering = "Qeytiyyad üçün təşəkkür edirik."

pleaseFillData = "Məlumatları doldurun"

registerTitle = "Qeydiyyat"

userPageTitle = "DJ-lər və redaktorlar"
inputSearch = "Axtarış"
active = "Aktiv"
all = "Hamısı"
editors = "Redaktorlar"
memberFrom = "-dan üzv"
postsNo = "Şərhlərin sayı:"
viewFullProfile = "Bütün profili izlə"

userProfile = "İstifadəci profili"
aboutProfile = "Haqqında:"
dateOfBirth = "Doğum tarixi"
commentsSent = "Şərhlər gödərildi:"
recommComm = "Məsləhətli şərhlər:"
gender = "Cins:"
organisation = "Təşkilat:"

pollTitle = "Səsvermə"
thankYouPoll = "Səsvermədə iştirak etdiyiniz üçün çox sağ olun!"
alreadyVoted = "Siz artıq səs vermisiz!"
numberOfVotes = "Ümumi səslərin sayı:"
pollButton = "İndi səs ver"
