### ka language template strings for Broadcaster 1.2 ### 

editArticle = "სტატიის რედაქტირება"
premium = "პრემიუმი*"
comments = "კომენტარი"
by = "მიერ"
readMore = " გაგრძელება "
addComment = "კომენტარი"
previous = "წინა"
next = "შემდეგი"
page = "გვერდი"
photo = "ფოტო"
welcome = "მოგესალმებით"
language = "ენა"
MakeYourOwnRadio = "შექმენი შენი საკუთარი რადიო"
CallForParticipation = "კონკურსი მონაწილეობის მისაღებად"
Join = "შემოგვიერთდი!"
articleGallery = "Article Gallery"
storyPlaces = "Story Places"
listenAudio = "მოუსმინეთ აუდიოს"
downloadAudioFile = "აუდიო ფაილის ჩამოტვირთვა"
watchVideo = "ვიდეოს ყურება"
download = "ჩამოტვირთვა"
file = "ფაილი"
downloadFile = "ფაილის ჩამოტვირთვა"
fileOfType = "File of type:"
alsoIn = "ასევე შიგნით"
relatedStories = " იგივე თემაზე"

viewProfile = "პროფილის ნახვა"

somethingToSay = "გაქვთ რამე სათქმელი?"
writeComment = "დაწერეთ კომენტარი"
anonymous = "ანონიმური"
writeAComment = "დაწერეთ კომენტარი"
commentNotAccepted = "თქვენი კომენტარი უარყოფილი იყო"
commentSentApproval = "თქვენი კომენტარი განსახილველად გადაიგზავნა"
publish = "გამოქვეყნება"
commentsLockedDisabled = "კომენტარის ფუნქცია ამ სტატიაზე გამორთულია"
